kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: tomcat
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: tomcat
    spec:
      containers:
      - name: tomcat
        image: argentum-web
        ports:
        - containerPort: 8080

---

kind: Service
apiVersion: v1
metadata:
  name: tomcat
spec:
  type: NodePort
  selector:
    app: tomcat
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: http
